
dev:
	python -m uvicorn sdxl_turbo_http:app --reload --reload-dir "." --reload-exclude ".env/*" --reload-delay 0.25 --host 127.0.0.1 --port 8088

run:
	python -m uvicorn sdxl_turbo_http:app --host 0.0.0.0 --port 8088
