version: '3.8'

services:
  redis:
    image: redis
    env_file: .env
    volumes:
      - ./volumes/redis:/data
      - ./docker/redis.conf:/redis.conf
      - ./docker/sysctl.conf:/etc/sysctl.conf
    restart: unless-stopped
    command: redis-server /redis.conf --bind 0.0.0.0
    network_mode: "host"

  discord_bot:
    build:
        context: .
        dockerfile: docker/Dockerfile
    command: bash -c "watchmedo auto-restart --interval 15 --patterns='*.py' --recursive python main.py"
    volumes:
      - ./src:/app
    env_file: .env
    network_mode: "host"
    depends_on:
        - redis

  celery_worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: bash -c "watchmedo auto-restart --patterns='*.py' --recursive /entrypoints/celery_worker.sh"
    volumes:
      - ./src:/app
    environment:
      - HOSTNAME_COMMAND='hostname -i'
    env_file: .env
    depends_on:
      - discord_bot
      - redis
    network_mode: "host"